datasetStores = ["/opt/mpidata", "/opt/data/MPS1", "/opt/data/HeadScanner", "/opt/data"]
brukerRecoStore = "/opt/data"
exportMDFFreqSpace = false
scanner = "" #"HeadScanner.toml"
enableRecoStore = true
